### ISSUE TITLE
Mejora aspecto tabla final de la función "criterio.Todos"

### ISSUE THREAD

**Issue by serbencab1** [serbencab1/TDtrabajo1Grupo2#2]
Creo que podríamos dar como resultado de dicha función una tabla con un mejor aspecto, ¿qué os pareced?

**Comment by ampjimjur** [comment]
### **Podemos mejorar las tablas con el paquete Knitr-kable o kableExtra y así podremos cambiar el aspecto de las filas cambiarle el color, dar una formato de salida: html . Además de poner nombres específicos a las columnas o incluir leyendas..

**Comment by enrperjim1** [comment]
Ya está incluida la mejora
